### ISSUE TITLE
Bedtools command clarification

### ISSUE THREAD

**Issue by Emiller88** [hyulab/PINTS#10]
In [Step II: Extract candidate enhancers](https://pints.yulab.org/tre_calling) I'm assuming it's `bedtools intersect` that's used, judging by the flags, but the commands are both

```sh
bedtools -a SampleA_1_bidirectional_peaks.bed -b promoters.bed -v > SampleA_1_bidirectional_peaks.distalTREs.bed
```
and
```sh
bedtools -a SampleA_1_bidirectional_peaks.bed -b exons.bed -f 0.6 -v > SampleA_1_bidirectional_peaks.nonexon.bed
```
Which are both missing the subcommand.

**Comment by liyao001** [comment]
You're right; we missed the subcommand (intersect) on that page. We fixed the typos, and the web page is now updated. Thanks a lot!
