### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by Emiller88** [hyulab/PINTS#11]
Are there any tests or usage examples for the `pints_caller`? I couldn't find any in [PINTS_analysis](https://github.com/hyulab/PINTS_analysis)

I've added a [nf-core module](https://github.com/nf-core/modules/blob/master/modules/pints/caller/main.nf) for it, but it failed with the test data we usually use, and I had to resort to the test dataset for groHMM.

**Comment by liyao001** [comment]
Great suggestion! I'll upload our unit test data set in the coming release and try to provide a complete example on our [TRE calling](https://pints.yulab.org/tre_calling) page.

**Comment by liyao001** [comment]
We have included unit test cases (with the small test data sets) in [our main repo](https://github.com/hyulab/PINTS/tree/main/tests) and added two case studies ([case 1](https://pints.yulab.org/tre_calling#part-iii-case-1) for GRO-cap and [case 2](https://pints.yulab.org/tre_calling#part-iv-case-2) for CoPRO) on our portal. I'll work on issue #12 this week and post updates once I have some.
