### ISSUE TITLE
[BUG] A lot of CSI files

### ISSUE THREAD

**Issue by adamwilliams749** [hyulab/PINTS#22]
**Describe the bug**
In a recent release, the running folder was left with many files ending in " CSI." Is this an intended behavior?

**Environment**
- Python version: [e.g. 3.7.16]
- PINTS version [e.g. 1.1.13]

**PINTS log file**
Please paste the log file in the report (usually named like `peakcalling_2022_01_01_01_01_123456.log`)

**Comment by liyao001** [comment]
Feel free to reopen this issue if the problem still exists.
